### ISSUE TITLE
Async requests

### ISSUE THREAD

**Issue by oliverbarnes** [liquidvotingio/decidim-module-liquidvoting#18]
Currently delegation creation and deletion reloads the page once it's done. 

It's a much nicer experience to use ajax instead, consistent with how the support button already works. 

Same goes for voting.

- [x] Voting (done on #25)
- [x] Delegations

**Comment by davefrey** [comment]
Update: 
Voting is now working cleanly on the current feature branch.
Delegation is working cleanly with page redirects, and moving to ajax calls has been problematic.

I propose we decouple this issue from PR #25

**Comment by oliverbarnes** [comment]
Makes sense 👍 I've updated the PR description accordingly

**Comment by davefrey** [comment]
Delegations part is now being worked on branch 18-async-delegations
