### ISSUE TITLE
Change the repo name to decidim-module-liquidvoting

### ISSUE THREAD

**Issue by oliverbarnes** [liquidvotingio/decidim-module-liquidvoting#26]
Just learned today that the naming convention for Decidim modules is `decidim-module-<name>`. It is more verbose, but I think it's important to respect it. We can open a discussion there down the line if we really feel strongly about simplifying module names.

**Comment by davefrey** [comment]
I like using their convention. The process looks simple and is well-documented here, including local rename: 
https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/renaming-a-repository

**Comment by oliverbarnes** [comment]
Are there any references to it we might be missing? We don't have any docker images including it yet, so we're good on that front

**Comment by davefrey** [comment]
apparently github is honoring/fwd’ing all repo references…old issues with a repo link etc

**Comment by oliverbarnes** [comment]
Done.

**Comment by davefrey** [comment]
Thanks. This then worked for me locally:
`git remote set-url origin git@github.com:liquidvotingio/decidim-module-liquidvoting.git`
