### ISSUE TITLE
Integrate proposal endorsements with the API

### ISSUE THREAD

**Issue by jinjagit** [liquidvotingio/decidim-module-liquidvoting#83]
Use LV api to record Decidim proposal endorsements as associated with respective voting_method, and update Decidim endorsement count using the LV voting_result for this `voting_method`.

Depends on completion of PR [#225] (https://github.com/liquidvotingio/api/issues/225).
See issue [#31](https://github.com/liquidvotingio/decidim-module-liquidvoting/issues/31) for context.

On completion, check if this has covered https://github.com/liquidvotingio/decidim-module-liquidvoting/issues/84

**Comment by davefrey** [comment]
Simon found out that groups and users can both independently endorse. Concept of delegation/voting weight doesn't really fit. 

Closing
