### ISSUE TITLE
Ensure voting_result(s) is/are updated accurately - on LV api & then to Decidim.

### ISSUE THREAD

**Issue by jinjagit** [liquidvotingio/decidim-module-liquidvoting#84]
Ensure 'correct' `voting_result`(s) is/are updated accurately (on LV api & then to Decidim), when/if delegate endorses/unendorses).

Follows on from issue [#83](https://github.com/liquidvotingio/decidim-module-liquidvoting/issues/83).

May not be necessary if [#83](https://github.com/liquidvotingio/decidim-module-liquidvoting/issues/83) covers this.

**Comment by oliverbarnes** [comment]
Yeah, this is just part of #83
