### ISSUE TITLE
Proposals main page needs to reflect supported/delegated

### ISSUE THREAD

**Issue by davefrey** [liquidvotingio/decidim-module-liquidvoting#89]
The main Proposals page doesn't reflect the vote/delegate status (the 1 Support = the current user):

![image](https://user-images.githubusercontent.com/29486/113435599-6e296d00-93e3-11eb-9311-cd7f728c5cac.png)

To replicate, go to a specific Proposal page, Support it, then go back to the main Proposals page (trim the proposal id from the url for example). The Support button remains enabled, and clicking it has no visible effect in the UI (the api call fails and a 500 is written to the rails log)

Here are some possible remedies:
- just make it minimally correct (dis/enable the Support button when proposal has been either supported or delegated by current_user)
- implement a version of the delegation UI in the Proposal card
- remove the Support button altogether from the Proposal card

**Comment by davefrey** [comment]
"Rejected" proposals remove the Support button; here's an example of how things would look when only showing the Supports (and Endorsements, thinking ahead) and now allowing voting on the main page:
![image](https://user-images.githubusercontent.com/29486/113436565-38858380-93e5-11eb-903b-36788b321cae.png)

So option 3 from above is the easiest for us, and is not so bad from a UX perspective

**Comment by oliverbarnes** [comment]
Technically not a bug, as it was never implemented :) But good catch, we didn't have it in our backlog yet.

Hiding the button for now is a good provisory solution, until we integrate things here too. We'll have to give it some careful design to keep this already busy card from becoming a mess...

**Comment by davefrey** [comment]
This is replaced by #104, I'm closing the current issue
