### ISSUE TITLE
Clean up overrides

### ISSUE THREAD

**Issue by oliverbarnes** [liquidvotingio/decidim-module-liquidvoting#91]
Use class_eval and override atomically, instead of overriding whole classes and modules.

This will shrink our diff surface when doing version bumps, and make things less prone for mistakes when updating.

**Comment by davefrey** [comment]
There may be translation keys in `en.yml` to remove as well; mixed feelings, it's nice to see the relevant keys for a UI like `_vote_button.html.erb` in one glance, but it's not DRY either.

**Comment by oliverbarnes** [comment]
IMO having the original module's locale files open right next to the overriden ones is easy enough, and the pain of having to check for updates (specially painful with locale files) is so not worth t :)
