### ISSUE TITLE
Create/delete delegation do not update the vote count

### ISSUE THREAD

**Issue by davefrey** [liquidvotingio/decidim-module-liquidvoting#94]
All four of the api mutations, (create|delete)_(vote|delegation), can alter the number of votes for a proposal. Currently, only the vote mutators are updating the proposals.proposal_vote_count which is displayed in the interface as "nnn Supports". But delegations affect the count as well when the delegate has already voted: the number of votes for a proposal will increase by the weight of the delegator (their own vote + any delegations naming them as delegate).

In the case of `create_delegation`, the `ApiClient` (and apparently the api itself, see liquidvotingio/api#189) return `true` instead of a response containing a `voting_result`. 

In the case of `delete_delegation`, there is a response containing a `voting_result` returned to the client, but our module code does not extract the new vote count and save it in the proposal.

**Comment by jinjagit** [comment]
`votingResult` can definitely be returned for (create|delete)_(vote|delegation) in the [current api PR #227](https://github.com/liquidvotingio/api/pull/227) I am working on, though I am not sure this was working correctly before (it _probably_ was). The `votingResult` query has to be present int the absinthe mutation operation(s), of course.

**Comment by jinjagit** [comment]
e.g:
![create_del](https://user-images.githubusercontent.com/3944042/114059746-96eeae00-988c-11eb-9c81-56c2eb9271f9.png)
![delete_del](https://user-images.githubusercontent.com/3944042/114060419-43309480-988d-11eb-9231-250fc1e3e768.png)
![create_vote](https://user-images.githubusercontent.com/3944042/114060428-462b8500-988d-11eb-9412-9ae0b617885d.png)
![delete_vote](https://user-images.githubusercontent.com/3944042/114060618-78d57d80-988d-11eb-989a-73fe8ca91e29.png)

**Comment by davefrey** [comment]
Oh this is excellent, thank you! It's not the api that is the problem but the parsed graphql query in api_client.rb in our module that specifies the return value. Today it's only returning the :id but I can change that to be a votingResult, then I can parse and return the suitable thing from the `ApiClient` 😀

I'll close the related issue liquidvotingio/api#189 I don't think we need anything in that repo.
