### ISSUE TITLE
Have delegation UI enforce choosing a delegate

### ISSUE THREAD

**Issue by davefrey** [liquidvotingio/decidim-module-liquidvoting#97]
Today a user can press Delegate Support without having selected a delegate from the dropdown. Given this view:

![image](https://user-images.githubusercontent.com/29486/114147659-36598280-9919-11eb-9862-c3ba69a35f02.png)

Clicking without choosing a delegate results in:

![image](https://user-images.githubusercontent.com/29486/114147601-22ae1c00-9919-11eb-90ea-094cb44a1edf.png)

The button click sends the request to the controller and then the api, where it silently fails, and the only visual change for the user is blanking out the prompt in the dropdown, which is a little confusing.

Ideally we should pop up a message "Choose your delegate" in those cases; unsure what the Decidim idiom is for that.

**Comment by jinjagit** [comment]
I don't get the same behavior, using either Firefox or Chromium.  

The "(choose delegate)" text remains in the select window when I click "Delegate Support" without selecting a delegate.  

Is this still as described in the issue description (maybe in other browsers... e.g Safari?), or has the behavior changed?  

If the "(choose delegate)" text remains in the select window, do we still want to inform the user of the need to select a delegate if the button is clicked without selecting a delegate? It seems unnecessary to me, if this is the case.

**Comment by davefrey** [comment]
Ah, good to know that blanking out the select text is browser specific.

And yes, we still need to prompt them, because what happens now is they click, the action fails but the error is invisible to the user. Better to insure in the button action that they've actually selected a delegate before they try to delegate.

**Comment by jinjagit** [comment]
> Ah, good to know that blanking out the select text is browser specific.
> 
> And yes, we still need to prompt them, because what happens now is they click, the action fails but the error is invisible to the user. Better to insure in the button action that they've actually selected a delegate before they try to delegate.

OK :+1:

**Comment by jinjagit** [comment]
BTW, I have not managed to find a similar use case - a select that is required before a related button push (form submit), in Decidim. If anyone knows of one, please let me know. Thanks.

**Comment by jinjagit** [comment]
Not (yet) found any pop-ups in Decidim, but there are lots of flash messages, usually at top of page.  

I am guessing we would prefer a flash message at the top of the page, not on the Delegation UI specifically?

**Comment by oliverbarnes** [comment]
It's a better user experience if the user receives a js pop up warning than waiting for the server to respond. That also saves us having to handle the bad form submittal on the server side

**Comment by jinjagit** [comment]
Closing, as addressed by #109
